### ISSUE TITLE
Add support themes

### ISSUE THREAD

**Issue by tobynet** [tobynet/longcat#2]
# Motivation 

* Support `Parallel universe`.
* For evil version of Longcat, `Tacgnol`  ( #1 )

## TODOs

* [x] Prototyping
* [x] 🤔 Resolve a question why suggest to use `pathname.ToSlash` in review?
  * [x] Write my comment in mattn/longcat#12
  * e.g.
    In `go version go1.10.4 linux/amd64`: 🥴? 

    ```golang
    gore> filepath.Join("/foo", `../../buzz\mytheme`, "foo.jpg")
    "/buzz\\mytheme/foo.jpg"

    gore> filepath.ToSlash(filepath.Join("/foo", `\mytheme`, "foo.jpg"))
    "/foo/\\mytheme/foo.jpg"

    gore> filepath.ToSlash(filepath.Join("/foo", `../../buzz\mytheme`, "foo.jpg"))
    "/buzz\\mytheme/foo.jpg"
    ```

    I know that `\` in filename allows in various(?) linux .

    In `go version go1.12.9 windows/amd64`: 

    ```golang
    gore> filepath.Join("/foo", `../../buzz\mytheme`, "foo.jpg")
    "\\buzz\\mytheme\\foo.jpg"

    gore> filepath.ToSlash(filepath.Join("/foo", `\mytheme`, "foo.jpg"))
    "/foo/mytheme/foo.jpg"

    gore> filepath.ToSlash(filepath.Join("/foo", `../../buzz\mytheme`, "foo.jpg"))
    "/buzz/mytheme/foo.jpg"
    ```
* [x] Add error handling in `loadTheme`, **for statik**
  * The theme does not always exist.
  * e.g. `-t wlongcat` (`wlongcat` does not exist in theme)
  * [x] List themes, get directory names in `/themes/*` using `statik`. 🤔 
    * [x] Research `statik` 
   ⇒ See this issue tobynet/longcat#4
* [x] Resolve a code smell in `loadThemeFromDir`. 
  ⇒ Decided more readable version tobynet/longcat@38e59679cc813740ac6c58a4d0e2a3694231806d
  * 🤔 The following is readable? 

    ```golang
    func (t *Theme) loadThemeFromDir(dir string) error {
        resources := []struct {
            img  *image.Image
            glob string
        }{
            {&t.Head, "*1.png"},
            {&t.Body, "*2.png"},
            {&t.Tail, "*3.png"},
        }

        for _, v := range resources {
            img, err := loadImageGlob(dir, v.glob)
            if err != nil {
                return err
            }
            *v.img = img
        }
        return nil
    }
    ```
 
  * or More Copy&Pastability

    ```golang
    func (t *Theme) loadThemeFromDir(dir string) error {
        var err error

        t.Head, err = loadImageGlob(dir, "*1.png")
        if err != nil {
            return err
        }
        t.Body, err = loadImageGlob(dir, "*2.png")
        if err != nil {
            return err
        }
        t.Tail, err = loadImageGlob(dir, "*3.png")
        if err != nil {
            return err
        }

        return nil
    }
    ```

  * `Theme` struct is wrong?
    ```golang
    // Theme of longcat
    type Theme struct {
        images [3]image.Image
    }

    func (t *Theme) Head() image.Image { return t.images[0] }
    func (t *Theme) Body() image.Image { return t.images[1] }
    func (t *Theme) Tail() image.Image { return t.images[2] }
    ```

  * or more human redable code?

ref. mattn/longcat#12
