### ISSUE TITLE
Add support horizontal mode

### ISSUE THREAD

**Issue by tobynet** [tobynet/longcat#3]
# Motivation 

* Optimize for the terminal stage.

## Technology survey

* [x] https://godoc.org/github.com/disintegration/imaging
  * Rotation

## Task

* [x] PoC of Rotation
* [x] Looks good?
----
* [x] Compatible with ...
  * [x] flipH
  * [x] flipV
  * [x] n
  * [x] l, i (number of columns,,,)
